services:
  db-postgres:
    image: postgres:16
    container_name: conviva-db-postgres
    environment:
      POSTGRES_DB: conviva_db
      POSTGRES_USER: conviva
      POSTGRES_PASSWORD: conviva
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conviva -d conviva_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app-conviva:
    build: .
    container_name: conviva-app
    depends_on:
      db-postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://conviva:conviva@db-postgres:5432/conviva_db
    ports:
      - "8000:8000"

volumes:
  pgdata:
